from datetime import datetime, timezone

from ..extensions import db


class Senior(db.Model):
    __tablename__ = 'seniors'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    nric_last4 = db.Column(db.String(5), nullable=False)
    photo_path = db.Column(db.String(255), nullable=True)
    registered_at = db.Column(
        db.DateTime, default=lambda: datetime.now(timezone.utc))
    is_active = db.Column(db.Boolean, default=True)

    presences = db.relationship(
        'SeniorPresence', backref='senior', lazy='dynamic')
    daily_summaries = db.relationship(
        'DailyPresenceSummary', backref='senior', lazy='dynamic')
    kiosk_events = db.relationship(
        'KioskEvent', backref='senior', lazy='dynamic')

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'nric_last4': self.nric_last4,
            'photo_path': self.photo_path,
            'registered_at': self.registered_at.isoformat()
            if self.registered_at else None,
            'is_active': self.is_active,
        }


class SeniorPresence(db.Model):
    __tablename__ = 'senior_presences'
    __table_args__ = (
        db.Index('ix_sp_senior_is_current', 'senior_id', 'is_current'),
        db.Index('ix_sp_room_is_current', 'room_id', 'is_current'),
        db.Index('ix_sp_is_current_status', 'is_current', 'status'),
    )

    id = db.Column(db.Integer, primary_key=True)
    senior_id = db.Column(
        db.Integer, db.ForeignKey('seniors.id'), nullable=True)
    room_id = db.Column(
        db.Integer, db.ForeignKey('rooms.id'), nullable=True)
    camera_id = db.Column(
        db.Integer, db.ForeignKey('cameras.id'), nullable=True)
    arrived_at = db.Column(
        db.DateTime, default=lambda: datetime.now(timezone.utc),
        index=True)
    last_seen_at = db.Column(
        db.DateTime, default=lambda: datetime.now(timezone.utc),
        index=True)
    status = db.Column(db.String(20), default='identified')
    is_current = db.Column(db.Boolean, default=True)

    room = db.relationship('Room', backref='presences')
    camera = db.relationship('Camera', backref='presences')

    def to_dict(self):
        return {
            'id': self.id,
            'senior_id': self.senior_id,
            'senior_name': self.senior.name if self.senior else None,
            'nric_last4': self.senior.nric_last4
            if self.senior else None,
            'photo_path': self.senior.photo_path
            if self.senior else None,
            'room_name': self.room.name if self.room else None,
            'room_id': self.room_id,
            'arrived_at': self.arrived_at.isoformat()
            if self.arrived_at else None,
            'last_seen_at': self.last_seen_at.isoformat()
            if self.last_seen_at else None,
            'status': self.status,
            'is_current': self.is_current,
        }


class DailyPresenceSummary(db.Model):
    """Pre-computed daily presence summary per senior per room.

    Generated by a scheduled job at the end of CCTV operating hours.
    This table is the source of truth for reports (member summary,
    weekly participation, duration per day).
    """
    __tablename__ = 'daily_presence_summaries'
    __table_args__ = (
        db.UniqueConstraint('senior_id', 'room_id', 'date',
                            name='uq_dps_senior_room_date'),
        db.Index('ix_dps_senior_date', 'senior_id', 'date'),
        db.Index('ix_dps_room_date', 'room_id', 'date'),
        db.Index('ix_dps_date', 'date'),
    )

    id = db.Column(db.Integer, primary_key=True)
    senior_id = db.Column(
        db.Integer, db.ForeignKey('seniors.id'), nullable=False)
    room_id = db.Column(
        db.Integer, db.ForeignKey('rooms.id'), nullable=True)
    date = db.Column(db.Date, nullable=False)

    # Aggregated stats for this senior in this room on this date
    total_seconds = db.Column(db.Integer, default=0)
    session_count = db.Column(db.Integer, default=0)
    first_seen = db.Column(db.DateTime, nullable=True)
    last_seen = db.Column(db.DateTime, nullable=True)

    # Metadata
    generated_at = db.Column(
        db.DateTime, default=lambda: datetime.now(timezone.utc))

    room = db.relationship('Room', backref='daily_summaries')

    def to_dict(self):
        return {
            'id': self.id,
            'senior_id': self.senior_id,
            'senior_name': self.senior.name if self.senior else None,
            'room_id': self.room_id,
            'room_name': self.room.name if self.room else None,
            'date': self.date.isoformat() if self.date else None,
            'total_seconds': self.total_seconds,
            'duration_formatted': (
                f'{self.total_seconds // 3600}h '
                f'{(self.total_seconds % 3600) // 60}m'
            ),
            'session_count': self.session_count,
            'first_seen': self.first_seen.isoformat()
            if self.first_seen else None,
            'last_seen': self.last_seen.isoformat()
            if self.last_seen else None,
            'generated_at': self.generated_at.isoformat()
            if self.generated_at else None,
        }
