"""Add identified_names to cctv_snapshots

Revision ID: 2c913467ff95
Revises: 8cc3b57d34a0
Create Date: 2026-03-06 18:30:58.248128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c913467ff95'
down_revision = '8cc3b57d34a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_presence_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['seniors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('senior_id', 'room_id', 'date', name='uq_dps_senior_room_date')
    )
    with op.batch_alter_table('daily_presence_summaries', schema=None) as batch_op:
        batch_op.create_index('ix_dps_date', ['date'], unique=False)
        batch_op.create_index('ix_dps_room_date', ['room_id', 'date'], unique=False)
        batch_op.create_index('ix_dps_senior_date', ['senior_id', 'date'], unique=False)

    with op.batch_alter_table('cctv_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identified_names', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cctv_snapshots', schema=None) as batch_op:
        batch_op.drop_column('identified_names')

    with op.batch_alter_table('daily_presence_summaries', schema=None) as batch_op:
        batch_op.drop_index('ix_dps_senior_date')
        batch_op.drop_index('ix_dps_room_date')
        batch_op.drop_index('ix_dps_date')

    op.drop_table('daily_presence_summaries')
    # ### end Alembic commands ###
