"""add moderate_threshold to rooms

Revision ID: 8cc3b57d34a0
Revises: a3f1b2c4d5e6
Create Date: 2026-03-06 11:24:48.741452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc3b57d34a0'
down_revision = 'a3f1b2c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_scheduled_time'), ['scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_status'), ['status'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_ack_type', ['acknowledged', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('cctv_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cctv_snapshots_camera_id'), ['camera_id'], unique=False)

    with op.batch_alter_table('kiosk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_events_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderate_threshold', sa.Integer(), nullable=True))

    with op.batch_alter_table('senior_presences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senior_presences_arrived_at'), ['arrived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_senior_presences_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index('ix_sp_is_current_status', ['is_current', 'status'], unique=False)
        batch_op.create_index('ix_sp_room_is_current', ['room_id', 'is_current'], unique=False)
        batch_op.create_index('ix_sp_senior_is_current', ['senior_id', 'is_current'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senior_presences', schema=None) as batch_op:
        batch_op.drop_index('ix_sp_senior_is_current')
        batch_op.drop_index('ix_sp_room_is_current')
        batch_op.drop_index('ix_sp_is_current_status')
        batch_op.drop_index(batch_op.f('ix_senior_presences_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_senior_presences_arrived_at'))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('moderate_threshold')

    with op.batch_alter_table('kiosk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_events_timestamp'))

    with op.batch_alter_table('cctv_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cctv_snapshots_camera_id'))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index('ix_alert_ack_type')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_status'))
        batch_op.drop_index(batch_op.f('ix_activities_scheduled_time'))

    # ### end Alembic commands ###
