"""add odoo_id to seniors

Revision ID: f04aa1c6bd60
Revises: 5d0f76ac740b
Create Date: 2026-04-06 11:30:48.198081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04aa1c6bd60'
down_revision = '5d0f76ac740b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seniors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odoo_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_seniors_odoo_id'), ['odoo_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seniors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seniors_odoo_id'))
        batch_op.drop_column('odoo_id')

    # ### end Alembic commands ###
